In [1]:
import numpy as np
from SequenceGame import SequenceEnv

env = SequenceEnv()

print(env.discs_on_board)
print(env.hand[0])
env.makeMove()
print(env.discs_on_board)


[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0 -1]]
[32 49 45 34  1  3 45]
makeMove played_card  32
playedcard id 32
drawCard played card 32
playerhand [32 49 45 34  1  3 45]
(array([0], dtype=int64),)
[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0 -1]]


In [2]:
for i in range(10):
    print(i)
    print(env.makeMove())
    print(env.discs_on_board)
    


0
makeMove played_card  28
playedcard id 28
drawCard played card 28
playerhand [28 33 28 11 12 29 35]
(array([0, 2], dtype=int64),)
None
[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  2  0  0  0  0  0  0  0 -1]]
1
makeMove played_card  3
playedcard id 3
drawCard played card 3
playerhand [20 49 45 34  1  3 45]
(array([5], dtype=int64),)
None
[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  2  0  0  0  0  0  0  0 -1]]
2
makeMove played_card  12
playedcard id 12
drawCard played card 12
pl