In [3]:
import numpy as np
from SequenceGame import SequenceEnv

env = SequenceEnv()

print(env.discs_on_board)
env.makeMove()
print(env.discs_on_board)

[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0 -1]]


NameError: name 'drawCard' is not defined

In [ ]:
from pprint import pprint
pprint(vars(env))
