In [2]:
import numpy as np
from SequenceGame import SequenceEnv

env = SequenceEnv()

print(env.discs_on_board)


[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0 -1]]


In [3]:
env.play_full_game()


makeMove played_card  37
playedcard id 37
drawCard played card 37
playerhand [47 28 20 37 13 32 46]
(array([3], dtype=int64),)
[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0 -1]]
makeMove played_card  34
playedcard id 34
drawCard played card 34
playerhand [49 27  0 45 30 34 49]
(array([5], dtype=int64),)
[[-1  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0 -1]]
makeMove played_card  13
playedcard id 13
drawCard played card 13
playerhand [47 28 

NameError: name 'env' is not defined